#!/usr/bin/env sh

if ! test $GITHUB_ACTIONS && ! test $SKIP; then
  if ! [[ -z $(git diff --name-only) ]]; then
    git add .
    SKIP=1 git commit -m "$(git log -1 --pretty="%B") (lint fix)"
  fi
fi


