#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if ! test $GITHUB_ACTIONS; then
  for ws in $(git diff --name-only --cached | grep -oE 'packages/([^/]+)' | uniq); do
    pnpm --filter="./${ws}" lint:fix
  done

  pnpm i
  git add pnpm-lock.yaml
fi

