#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm -r lint
pnpm i

if $(git diff --name-only --cached | grep -q '^pnpm-lock.yaml$'); then
  git add pnpm-lock.yaml
  git commit -m 'chore: update lockfile'
fi

