#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if ! test $GITHUB_ACTIONS && ! test $SKIP; then
  pnpm i
  for ws in $(git diff --name-only --cached | grep -oP '^(packages/([^/\.]+)|playground)(?=/)' | uniq); do
    pnpm --filter="./${ws}" lint:fix
  done
else
  pnpm i --no-frozen-lockfile
fi

git add pnpm-lock.yaml

