name: Continuos Integration

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: |
          pnpm --no-bail --filter='./packages/types' build \
            && pnpm --no-bail --filter='./packages/common' build \
            && pnpm --no-bail --filter='./packages/entrypoint' build \
            && pnpm --no-bail --filter='./packages/validation' build \
            && pnpm --no-bail --filter='./packages/http' build \
            && pnpm --no-bail --filter='./packages/node-http' build \
            && pnpm --no-bail --filter='./packages/access-control' build \
            && pnpm --no-bail --filter='./packages/security' build \
            && pnpm --no-bail --filter='./packages/api' build \
            && pnpm --no-bail --filter='./packages/builtins' build \
            && pnpm --no-bail --filter='./packages/server' build \
            && pnpm --no-bail --filter='./packages/aeria' build \
            && pnpm --no-bail --filter='./packages/aeria-build' build:build

      - name: Patch node_modules
        run: |
          find packages -mindepth 1 -maxdepth 1 \
            -exec bash -c 'a={}; cp -r $a/dist node_modules/@aeriajs/${a//packages\//} 2>/dev/null || true' \;
          cp -r packages node_modules/@aeriajs

      - name: Build playground
        run: |
          cd playground
          pnpm install .
          pnpm build

      - name: Run tests
        run: pnpm -r test

