name: Continuos Integration

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.changeset/**'
      - 'packages/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build packages
        run: pnpm build
      - name: Typecheck tests
        run: pnpm -r 'test:typecheck'
      - name: Run tests
        run: pnpm -r test
      - name: Build playground
        run: pnpm --filter=playground build
      - name: Create release PR
        uses: changesets/action@v1
        with:
          publish: ./.github/scripts/publish.sh
        env:
          BRANCH_NAME: ${{ github.ref_name  }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

